services:
  db:
    image: postgres:17
    container_name: frimmy-db
    environment:
      POSTGRES_DB: frimmy
      POSTGRES_USER: frimmy
      POSTGRES_PASSWORD: frimmy
    ports:
      - "5432:5432"
    volumes:
      - frimmy-pgdata:/var/lib/postgresql/data

volumes:
  frimmy-pgdata:
