-- 재료(ingredient) 테이블 — com.frimmy.domain.Ingredient 매핑
-- IF NOT EXISTS: 기존 ddl-auto로 만든 테이블이 있어도 충돌 없이 통과 (개발 초기 전환 대응)
CREATE TABLE IF NOT EXISTS ingredient (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    category        VARCHAR(255),
    quantity        DOUBLE PRECISION,
    unit            VARCHAR(255),
    expiration_date DATE,
    created_at      TIMESTAMP
);
